#!/bin/sh
set -eu

test -z "$(gofmt -l $(git ls-files '*.go'))"
git diff --check
go mod verify
go mod tidy -diff
go test -count=1 ./...
go test -race -count=1 ./...
go vet ./...
go run golang.org/x/vuln/cmd/govulncheck@v1.7.0 ./...
